import streamlit as st
import pandas as pd
from utils.data_loader import compute_sales_metrics, compute_elasticity_data
from agents.pricing_agent import PricingAgent
from agents.inventory_agent import InventoryAgent
from agents.promotion_agent import PromotionAgent


def render():
    st.markdown("""
    <div class="page-header">
        <div class="page-title">📋 Markdown Planner</div>
        <div class="page-subtitle">
            Price IQ · Agent #5 · Clear inventory profitably
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Load data ──────────────────────────────────────────────────────────
    with st.spinner("Loading products..."):
        metrics       = compute_sales_metrics()
        elasticity_df = compute_elasticity_data()

    # ── Filters ────────────────────────────────────────────────────────────
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        risk_filter = st.multiselect(
            "Clearance Risk",
            ["HIGH", "MEDIUM", "LOW"],
            default=["HIGH", "MEDIUM"],
        )
    with col2:
        abc_filter = st.multiselect(
            "ABC Class",
            ["A", "B", "C"],
            default=["A", "B", "C"],
        )
    with col3:
        cat_filter = st.selectbox(
            "Category",
            ["All"] + sorted(metrics["main_category"].unique().tolist()),
        )
    with col4:
        max_products = st.slider("Products to show", 5, 50, 10)

    # ── Filter products ────────────────────────────────────────────────────
    filtered = metrics[
        (metrics["clearance_risk"].isin(risk_filter)) &
        (metrics["abc_class"].isin(abc_filter))
    ]
    if cat_filter != "All":
        filtered = filtered[filtered["main_category"] == cat_filter]

    filtered = filtered.sort_values(
        "days_of_stock", ascending=False
    ).head(max_products)

    st.markdown(
        f"<div style='font-size:0.8rem;color:#6b7280;margin-bottom:1rem;'>"
        f"Showing {len(filtered)} products — "
        f"Markdown ladders generated by AI agents</div>",
        unsafe_allow_html=True,
    )

    if filtered.empty:
        st.warning("No products match the selected filters.")
        return

    # ── Initialise agents ──────────────────────────────────────────────────
    pricing_agent   = PricingAgent()
    inventory_agent = InventoryAgent()
    promo_agent     = PromotionAgent()

    # ── Render ladder card per product ────────────────────────────────────
    for _, row in filtered.iterrows():
        pid = row["product_id"]

        # Get elasticity
        elast_row  = elasticity_df[elasticity_df["product_id"] == pid]
        elasticity = float(elast_row["elasticity"].mean()) \
                     if not elast_row.empty else -1.2

        product = row.to_dict()
        product["elasticity"]               = elasticity
        product["recommended_markdown_pct"] = 15
        product["forecast_days"]            = 30

        # Run agents
        pricing_out  = pricing_agent.analyze(product)
        inventory_out= inventory_agent.analyze(product)
        promo_out    = promo_agent.analyze(product)

        recommended_pct = pricing_out.data.get("markdown_pct", 15)
        urgency         = inventory_out.data.get("urgency", "MEDIUM")
        promo_type      = promo_out.data.get("promo_type", "none")

        # Build ladder steps
        steps = _build_ladder(recommended_pct)

        # Status badge
        if urgency == "CRITICAL":
            status_color = "#dc2626"
            status_label = "CRITICAL"
        elif urgency == "HIGH":
            status_color = "#f59e0b"
            status_label = "ACTIVE"
        else:
            status_color = "#16a34a"
            status_label = "MONITOR"

        price     = float(row["price"])
        cost      = float(row.get("cost_price", price * 0.55))
        new_price = price * (1 - recommended_pct / 100)
        margin    = ((new_price - cost) / new_price * 100) if new_price > 0 else 0
        dos       = int(row.get("days_of_stock", 0))
        st_rate   = float(row.get("sell_through_rate", 0))
        qty       = int(row.get("quantity", 0))

        # ── Card HTML ──────────────────────────────────────────────────────
        st.markdown(f"""
        <div class="ladder-card">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.75rem;">
                <div class="ladder-card-title">{row['product_name']}</div>
                <span style="background:{status_color}20; color:{status_color};
                             font-size:0.7rem; font-weight:700;
                             padding:2px 10px; border-radius:10px;">
                    {status_label}
                </span>
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Ladder steps as columns
        step_cols = st.columns(len(steps))
        for i, (step_pct, step_label) in enumerate(steps):
            is_active    = abs(step_pct - recommended_pct) < 5
            is_completed = step_pct < recommended_pct - 5
            step_price   = price * (1 - step_pct / 100)

            if is_completed:
                css = "ladder-step ladder-step-completed"
            elif is_active:
                css = "ladder-step ladder-step-active"
            else:
                css = "ladder-step"

            step_cols[i].markdown(f"""
            <div class="{css}">
                -{step_pct:.0f}%<br>
                <span style="font-size:0.7rem;font-weight:400;">
                    {step_label}
                </span>
            </div>
            """, unsafe_allow_html=True)

        # Product meta row
        st.markdown(f"""
        <div class="ladder-meta" style="margin-top:0.5rem;">
            <b>{row['product_id']}</b> ·
            {row['main_category']} ·
            <b>₹{new_price:,.0f}</b>
            <span style="color:#9ca3af;">(was ₹{price:,.0f})</span> ·
            ST: <b style="color:{'#dc2626' if st_rate < 50 else '#16a34a'}">
                {st_rate:.0f}%</b> / 95% ·
            {qty} units left ·
            Margin: <b>{margin:.0f}%</b> ·
            DOS: <b>{dos}d</b> ·
            Promo: <b>{promo_type}</b> ·
            Agent: 🤖 {pricing_out.agent_name}
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<div style='margin-bottom:1rem'></div>",
                    unsafe_allow_html=True)


def _build_ladder(recommended_pct: float) -> list:
    """
    Build 4-step markdown ladder around the recommended %.
    Returns list of (pct, label) tuples.
    """
    rec = round(recommended_pct / 5) * 5  # round to nearest 5

    if rec <= 10:
        steps = [(5,  "2wk"), (10, "2wk velocity"),
                 (15, "2wk"), (20, "2wk")]
    elif rec <= 20:
        steps = [(10, "2wk"), (20, "2wk velocity"),
                 (30, "2wk"), (40, "2wk")]
    elif rec <= 35:
        steps = [(15, "2wk"), (25, "2wk velocity"),
                 (35, "2wk"), (50, "2wk")]
    else:
        steps = [(20, "2wk"), (35, "2wk velocity"),
                 (45, "2wk"), (55, "2wk")]

    return steps
